### PR TITLE
Clean the GeneralContext with useSettings custom hook

### PR DESCRIPTION
**Pull request by ErezBiren**
Hi, 
Did a new custom hook that groups together all the settings states.
and reduces the size of GeneralContext.tsx for better separation of concerns

### CODE REVIEW

**Review by yonatanmgr — CHANGES_REQUESTED** [review]
Great idea! 
I do have one fix if we're already dealing with the settings - can you adjust it so the language won't change every time the user refreshes?

**Comment by ErezBiren** [comment]
> Great idea! I do have one fix if we're already dealing with the settings - can you adjust it so the language won't change every time the user refreshes?

Do you mean to save it to local storage?
Currently I don't have time to do that so I think it would better to do that in another PR

**Comment by yonatanmgr** [comment]
That's fine then, I'll open an issue and work on it sometime later!
Merging

**Review by yonatanmgr — APPROVED** [review]

**Comment by yonatanmgr** [comment]
@ErezBiren Just fixed the language localStorage bug, so forget about what I said :)

**Pull request merged**
